# Generated by Django 3.2.9 on 2021-11-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='twit',
            table='twits',
        ),
    ]
